application: geoyoutube
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: search.html
  upload: search.html
  
- url: /search
  static_files: search.html
  upload: search.html
  
- url: /about
  static_files: about.html
  upload: about.html
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js